services:
  backend:
    build:
      context: ./container-assets/backend
      dockerfile: Dockerfile-php
    container_name: backend
    restart: "no"
    volumes:
      - backend-tmp:/tmp
      - backend-root-folder:/root
      - .:/var/www/
      - ./container-assets/backend/php-xdebug.ini:/usr/local/etc/php/conf.d/php-xdebug.ini
    networks:
      - network
    ports:
      - "8123:80"
    command: "php -S 0.0.0.0:80"
    working_dir: /var/www/backend/public
    env_file: .env
    environment:
      - DB_CONNECTION=mariadb
      - DB_HOST=${MARIADB_HOST}
      - DB_PORT=${MARIADB_PORT}
      - DB_DATABASE=${MARIADB_DATABASE}
      - DB_USERNAME=${MARIADB_USER}
      - DB_PASSWORD=${MARIADB_PASSWORD}

  frontend:
    image: node:22-alpine
    container_name: frontend
    restart: "no"
    volumes:
      - ./frontend:/var/www/
      - frontend-root-folder:/root
      - ./container-assets/frontend/dev-server.sh:/var/www/dev-server.sh

    working_dir: /var/www
    ports:
      - "8000:80"
      - "9000:9000"
    command: "sh ./dev-server.sh"

  #Database
  db:
    image: mariadb:12
    container_name: db
    ports:
        # The HTTP port
        - "33006:3306"
    restart: "no"
    tty: true
    volumes:
        - db:/var/lib/mysql
    networks:
        - network
    env_file: .env

volumes:
  backend-tmp:
  db:
  frontend-root-folder:
  backend-root-folder:

networks:
  network: {}
