FROM php:8.5-alpine

RUN apk add --no-cache --update linux-headers \
    && apk add --no-cache $PHPIZE_DEPS \
    && apk add bash \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && wget https://raw.githubusercontent.com/composer/getcomposer.org/f3108f64b4e1c1ce6eb462b159956461592b3e3e/web/installer -O - -q | php -- --quiet

RUN mv /composer.phar /usr/bin/composer
